### ISSUE TITLE
Error 400 on binance

### ISSUE THREAD

**Issue by njbrown09** [GuntharDeNiro/BTCT#351]
https://gyazo.com/0484e4581dab5c8423e9d85a3e37913a

**Comment by njbrown09** [comment]
Fixed. 

solution (windows 10):
1. Right click the clock in the task bar and click "Adjust date and time" 
2. Disable "Set time automatically"
2. Change the computer time 5 minutes ahead
3. Enable "Set time automatically"
4. Start the bot 😃

**Comment by pmh2017** [comment]
I have the same issue and error message, and this bug is not resolved for me at least: I have tried both the automatic time reset solution and hard server reboot, with no luck. 

Am running a VPS on Contabo with Windows Server 2012R2, trying to use Binance. 

> 
> Loading config...
> Loading exchange - binance
> error: fetchMyTrades
> Error: Response code 400
>     at Request.module.exports._makeRequest.request [as _callback] (C:\snapshot\Gunbot-master\ctx\helper\binance\binance-api.js:0:0)
>     at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
>     at emitTwo (events.js:125:13)
>     at Request.emit (events.js:213:7)
>     at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
>     at emitOne (events.js:115:13)
>     at Request.emit (events.js:210:7)
>     at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
>     at Object.onceWrapper (events.js:312:19)
>     at emitNone (events.js:110:20)
>     at IncomingMessage.emit (events.js:207:7)
>     at endReadableNT (_stream_readable.js:1045:12)
>     at _combinedTickCallback (internal/process/next_tick.js:102:11)
>     at process._tickCallback (internal/process/next_tick.js:161:9)
> 

> (node:3652) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Response code 400
(node:3652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lbn21** [comment]
@njbrown09 thanks. Worked for me on Windows 10

**Comment by yashspatel23** [comment]
@pmh2017 can you run this on your local computer to see if the error appears? If it does not, then the issue lies with the VPS you are using.

**Comment by mobiledan121** [comment]
I may have found a fix here
https://gunbot.shop/error-response-code-400-on-binance-how-to-fix/
For me, I had to add a second API key and up she came.

Thanks to GunbotShop
