### ISSUE TITLE
Charts not showing in dashboard when connecting via Virtual Private Server

### ISSUE THREAD

**Issue by jbrelin** [GuntharDeNiro/BTCT#469]
From my personal machine, the charts on the dashboard appear fine, but the charts on the dashboard from my Virtual Private Server appear as follows forever:

![gunbot bug](https://user-images.githubusercontent.com/28735349/35487665-2552351e-0433-11e8-9bea-5453908e04f5.png)

Otherwise, thank you for the update!

**Comment by jbrelin** [comment]
To clarify, from within the VPS service console, the charts are working fine. However, when opening up port 5000 and connecting via an external browser, I see the problem.

**Comment by balroh** [comment]
Go to `Settings` then `Web sockets` and change the `hostname` in the configuration to the IP/hostname of you VPS. Then `Save` and restart the bot. It should now work. 

Credit goes to https://gunthy.org/forum/index.php/topic,2834.0.html

**Comment by jbrelin** [comment]
I am sorry, that did not fix the problem. The exact same issue appears. I am thinking I may need to open up some ports on the VPS? If so, do you know what those ports are?

Thanks

**Comment by jbrelin** [comment]
One more thing, I see the charts in the setup screen, but not in the dashboard screen. I have opened up ports 500, 5634, and 3000 in my VPS for both inbound and outbound. Still same problem.

**Comment by jbrelin** [comment]
I wonder if these errors are related:...
![image](https://user-images.githubusercontent.com/28735349/35783711-9b8c619a-09c0-11e8-9d13-ac9e76ef8188.png)
