### ISSUE TITLE
inconsistent usage of number formatting

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/BTCT#9]
Sometimes values are printed as 0.12344001122, sometimes as 5443.2210 (which really should be printed as 0.54432210), sometimes printed as 7.1e-7, sometimes printed as price to buy: 7.679280000000009e-7

It's extremely frustrating to "see" what's going on with the bot when numbers are not formatted consistently.

Please fix the code so that all numbers are formatted properly to the correct number of significant digits.

**Comment by asymmetric** [comment]
Is there any sign that the author is even reading these issues?

AFAIK all support is on the gunthy.org forum.

**Comment by utdrmac** [comment]
I tagged author in Telegram for this bug but who knows. I'll cross post in forum.

**Comment by GuntharDeNiro** [comment]
will parseFloat those values even if it is cosmetic: that's scientific notation of low floats

**Comment by utdrmac** [comment]
Still on 4.0.5. And it happens inconsistently. I would expect there to be one common "output" function that all things pass through and so fixing it in 1 place fixes all output.

```
2017/08/24 00:11:20: BTC_BCN Last Bid/Ask 3.2e-7/3.3e-7
2017/08/24 00:11:20: Got Trading History
2017/08/24 00:11:20: Averaged bought price: 4.3e-7
2017/08/24 00:11:20: Price to sell: 4.386e-7
2017/08/24 00:11:20: EMA1: 0.00000032/EMA2: 0.00000032
2017/08/24 00:11:20: Price to buy: 3.136e-7
2017/08/24 00:11:21: Got Open Orders
2017/08/24 00:11:21: Last Bid/Price to sell: 3.2e-7/4.386e-7
2017/08/24 00:11:21: Last Ask/Price to buy: 3.3e-7/3.136e-7
2017/08/24 00:11:21: Trend for BTC_BCN:    DOWN!!!
Nothing changed in BTC_BCN: Bid/Ask is 3.2e-7/3.3e-7. Entry points are: 3.136e-7/4.386e-7
```

**Comment by GuntharDeNiro** [comment]
Fixed scientific notation ToFixed(8) in v5
Thanks for reporting this!

**Comment by utdrmac** [comment]
@GuntharDeNiro This doesn't appear to be fixed in 5.0.1

```
------------------------------------------------------------------------------------------------
 ɢƱƝƁѺŦ v5.0.1  Scanning poloniex for trading opportunities 2017/09/13 05:35:11
------------------------------------------------------------------------------------------------
2017/09/13 05:35:11: BTC_DOGE Last Bid/Ask 0.00000034/0.00000035
2017/09/13 05:35:11: Got Trading History
2017/09/13 05:35:12: Averaged bought price: 4.6618705035971177e-7
2017/09/13 05:35:12: Price to sell: 4.736460431654671e-7
2017/09/13 05:35:12: EMA1: 0.00000037/EMA2: 0.00000036
2017/09/13 05:35:12: Price to buy: 0.00000035
2017/09/13 05:35:12: Got Open Orders
2017/09/13 05:35:12: Last Bid/Price to sell: 0.00000034/0.00000047
2017/09/13 05:35:12: Last Ask/Price to buy: 0.00000035/0.00000035
------------------------------------------------------------------------------------------------
EMA1: 0.00000037 == EMA2: 0.00000036
------------------------------------------------------------------------------------------------
2017/09/13 05:35:12: Trend for BTC_DOGE:    DOWN!!!
2017/09/13 05:35:12: We are on level 2 to sell (bought/sell at): 4.6618705035971177e-7/4.736460431654671e-7
2017/09/13 05:35:12: There are some trading opportunities for BTC_DOGE at poloniex. Scanning Trade History
2017/09/13 05:35:12: Last Bid price BTC_DOGE: 3.4e-7 | Last Ask: 3.5e-7
```

**Comment by utdrmac** [comment]
@GuntharDeNiro Still broken in 5.0.5

![screen shot 2017-09-29 at 8 16 51 pm](https://user-images.githubusercontent.com/4413670/31040946-4fac082e-a553-11e7-8d84-870b2cc9cf38.png)
